version: '3.7'

services:
  app_python:
    image: simonwt/moscow-time-fastapi:latest
    ports:
       - "8001:8001"
    networks:
      - monitoring.network
    logging:
        driver: "json-file"
        options:
          max-size: "100m"
          tag: "{{.ImageName}}"

  grafana:
    image: grafana/grafana:7.3.4
    container_name: monitoring.grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ${PWD}/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - VIRTUAL_HOST=monitoring.grafana
      - NETWORK_ACCESS=internal
      - VIRTUAL_PORT=3000
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - monitoring.network
    labels:
      org.label-schema.group: "monitoring"

  promtail:
    image: grafana/promtail:2.5.0
    container_name: monitoring.promtail
    expose:
      - 9080
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-data:/var/lib/promtail/positions
      - ${PWD}/promtail/promtail.yml:/etc/promtail/promtail.yml
    command:
      - '-config.file=/etc/promtail/promtail.yml'
    restart: unless-stopped
    networks:
      - monitoring.network
    labels:
      org.label-schema.group: "monitoring"

  loki:
    container_name: monitoring.loki
    image: grafana/loki:2.5.0
    expose:
      - 3100
    ports:
      - "3100:3100"
    restart: unless-stopped
    networks:
      - monitoring.network
    labels:
      org.label-schema.group: "monitoring"

networks:
  monitoring.network:
    ipam:
      driver: default

volumes:
  grafana-data: {}
  loki-data: {}
  promtail-data: {}